//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Wadd.Core.Localization;

/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute]
public class Strings
{
    private static global::System.Resources.ResourceManager? resourceMan;
    private static global::System.Globalization.CultureInfo? resourceCulture;

    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Strings()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager
    {
        get
        {
            if (object.ReferenceEquals(resourceMan, null))
            {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wadd.Core.Localization.Strings", typeof(Strings).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string? Get(string name, global::System.Globalization.CultureInfo? culture = null)
    {
        return ResourceManager.GetString(name, culture ?? resourceCulture);
    }

    public static string App_Title => ResourceManager.GetString("App_Title", resourceCulture) ?? "Wadd";
    public static string Nav_Tasks => ResourceManager.GetString("Nav_Tasks", resourceCulture) ?? "Tasks";
    public static string Nav_Calendar => ResourceManager.GetString("Nav_Calendar", resourceCulture) ?? "Calendar";
    public static string Nav_Goals => ResourceManager.GetString("Nav_Goals", resourceCulture) ?? "Goals";
    public static string Nav_Search => ResourceManager.GetString("Nav_Search", resourceCulture) ?? "Search";
    public static string Nav_Settings => ResourceManager.GetString("Nav_Settings", resourceCulture) ?? "Settings";
    public static string Nav_CompletedTasks => ResourceManager.GetString("Nav_CompletedTasks", resourceCulture) ?? "Completed Tasks";
    public static string Nav_RecurringTasks => ResourceManager.GetString("Nav_RecurringTasks", resourceCulture) ?? "Recurring Tasks";
    public static string Nav_TagsManagement => ResourceManager.GetString("Nav_TagsManagement", resourceCulture) ?? "Tags Management";
    public static string Nav_ConflictCenter => ResourceManager.GetString("Nav_ConflictCenter", resourceCulture) ?? "Conflict Center";

    public static string Common_Add => ResourceManager.GetString("Common_Add", resourceCulture) ?? "Add";
    public static string Common_Save => ResourceManager.GetString("Common_Save", resourceCulture) ?? "Save";
    public static string Common_Cancel => ResourceManager.GetString("Common_Cancel", resourceCulture) ?? "Cancel";
    public static string Common_Delete => ResourceManager.GetString("Common_Delete", resourceCulture) ?? "Delete";
    public static string Common_Edit => ResourceManager.GetString("Common_Edit", resourceCulture) ?? "Edit";
    public static string Common_Done => ResourceManager.GetString("Common_Done", resourceCulture) ?? "Done";
    public static string Common_Close => ResourceManager.GetString("Common_Close", resourceCulture) ?? "Close";
    public static string Common_Search => ResourceManager.GetString("Common_Search", resourceCulture) ?? "Search...";
    public static string Common_Filter => ResourceManager.GetString("Common_Filter", resourceCulture) ?? "Filter";
    public static string Common_All => ResourceManager.GetString("Common_All", resourceCulture) ?? "All";
    public static string Common_Today => ResourceManager.GetString("Common_Today", resourceCulture) ?? "Today";
    public static string Common_Tomorrow => ResourceManager.GetString("Common_Tomorrow", resourceCulture) ?? "Tomorrow";
    public static string Common_Upcoming => ResourceManager.GetString("Common_Upcoming", resourceCulture) ?? "Upcoming";
    public static string Common_Overdue => ResourceManager.GetString("Common_Overdue", resourceCulture) ?? "Overdue";
    public static string Common_NoDueDate => ResourceManager.GetString("Common_NoDueDate", resourceCulture) ?? "No Due Date";
    public static string Common_Loading => ResourceManager.GetString("Common_Loading", resourceCulture) ?? "Loading...";
    public static string Common_Retry => ResourceManager.GetString("Common_Retry", resourceCulture) ?? "Retry";
    public static string Common_Confirm => ResourceManager.GetString("Common_Confirm", resourceCulture) ?? "Confirm";
    public static string Common_Back => ResourceManager.GetString("Common_Back", resourceCulture) ?? "Back";

    public static string Tasks_QuickAddPlaceholder => ResourceManager.GetString("Tasks_QuickAddPlaceholder", resourceCulture) ?? "Add a task... (e.g. Call John tomorrow at 2pm)";
    public static string Tasks_EmptyTitle => ResourceManager.GetString("Tasks_EmptyTitle", resourceCulture) ?? "No tasks found";
    public static string Tasks_EmptySubtitle => ResourceManager.GetString("Tasks_EmptySubtitle", resourceCulture) ?? "You're all caught up! Enjoy your day.";
    public static string Tasks_Title => ResourceManager.GetString("Tasks_Title", resourceCulture) ?? "Title";
    public static string Tasks_Description => ResourceManager.GetString("Tasks_Description", resourceCulture) ?? "Description";
    public static string Tasks_DueDate => ResourceManager.GetString("Tasks_DueDate", resourceCulture) ?? "Due Date";
    public static string Tasks_Reminder => ResourceManager.GetString("Tasks_Reminder", resourceCulture) ?? "Reminder";
    public static string Tasks_Priority => ResourceManager.GetString("Tasks_Priority", resourceCulture) ?? "Priority";
    public static string Tasks_Priority_Low => ResourceManager.GetString("Tasks_Priority_Low", resourceCulture) ?? "Low";
    public static string Tasks_Priority_Normal => ResourceManager.GetString("Tasks_Priority_Normal", resourceCulture) ?? "Normal";
    public static string Tasks_Priority_High => ResourceManager.GetString("Tasks_Priority_High", resourceCulture) ?? "High";
    public static string Tasks_Priority_Urgent => ResourceManager.GetString("Tasks_Priority_Urgent", resourceCulture) ?? "Urgent";
    public static string Tasks_Layout_Standard => ResourceManager.GetString("Tasks_Layout_Standard", resourceCulture) ?? "Standard List";
    public static string Tasks_Layout_Compact => ResourceManager.GetString("Tasks_Layout_Compact", resourceCulture) ?? "Compact List";
    public static string Tasks_Layout_Cards => ResourceManager.GetString("Tasks_Layout_Cards", resourceCulture) ?? "Card Grid";

    public static string Settings_Title => ResourceManager.GetString("Settings_Title", resourceCulture) ?? "Settings";
    public static string Settings_General => ResourceManager.GetString("Settings_General", resourceCulture) ?? "GENERAL & LAYOUT";
    public static string Settings_TasksLayout => ResourceManager.GetString("Settings_TasksLayout", resourceCulture) ?? "Task List Layout";
    public static string Settings_TasksLayout_Desc => ResourceManager.GetString("Settings_TasksLayout_Desc", resourceCulture) ?? "Choose how your tasks are displayed in the main list.";
    public static string Settings_UpcomingRange => ResourceManager.GetString("Settings_UpcomingRange", resourceCulture) ?? "Upcoming Tasks Range";
    public static string Settings_UpcomingRange_Desc => ResourceManager.GetString("Settings_UpcomingRange_Desc", resourceCulture) ?? "Number of days ahead to include in the upcoming view.";
    public static string Settings_ShowNotePreviews => ResourceManager.GetString("Settings_ShowNotePreviews", resourceCulture) ?? "Show Note Previews";
    public static string Settings_ShowNotePreviews_Desc => ResourceManager.GetString("Settings_ShowNotePreviews_Desc", resourceCulture) ?? "Display the first few lines of notes beneath each task item.";

    public static string Settings_Notifications => ResourceManager.GetString("Settings_Notifications", resourceCulture) ?? "NOTIFICATIONS & REMINDERS";
    public static string Settings_EnableNotifications => ResourceManager.GetString("Settings_EnableNotifications", resourceCulture) ?? "Enable Notifications";
    public static string Settings_EnableNotifications_Desc => ResourceManager.GetString("Settings_EnableNotifications_Desc", resourceCulture) ?? "Allow Wadd to send alerts for task reminders, due dates, and overdue tasks.";
    public static string Settings_TaskReminders => ResourceManager.GetString("Settings_TaskReminders", resourceCulture) ?? "Task Reminders";
    public static string Settings_TaskReminders_Desc => ResourceManager.GetString("Settings_TaskReminders_Desc", resourceCulture) ?? "Send an alert when a scheduled task reminder is triggered.";
    public static string Settings_DueDates => ResourceManager.GetString("Settings_DueDates", resourceCulture) ?? "Due Date Alerts";
    public static string Settings_DueDates_Desc => ResourceManager.GetString("Settings_DueDates_Desc", resourceCulture) ?? "Send an alert on the day a task is due.";
    public static string Settings_Overdue => ResourceManager.GetString("Settings_Overdue", resourceCulture) ?? "Overdue Alerts";
    public static string Settings_Overdue_Desc => ResourceManager.GetString("Settings_Overdue_Desc", resourceCulture) ?? "Alert about unfinished tasks past their due date.";
    public static string Settings_LeadTime => ResourceManager.GetString("Settings_LeadTime", resourceCulture) ?? "Advance Notice";
    public static string Settings_LeadTime_Desc => ResourceManager.GetString("Settings_LeadTime_Desc", resourceCulture) ?? "How early to alert before a scheduled reminder or due date.";
    public static string Settings_RepeatInterval => ResourceManager.GetString("Settings_RepeatInterval", resourceCulture) ?? "Repeat Notification Interval";
    public static string Settings_RepeatInterval_Desc => ResourceManager.GetString("Settings_RepeatInterval_Desc", resourceCulture) ?? "Repeatedly notify until the task is completed or dismissed.";
    public static string Settings_NotificationSound => ResourceManager.GetString("Settings_NotificationSound", resourceCulture) ?? "Notification Sound";
    public static string Settings_NotificationSound_Desc => ResourceManager.GetString("Settings_NotificationSound_Desc", resourceCulture) ?? "Play a chime when an alert or reminder arrives.";
    public static string Settings_TaskCompletionSound => ResourceManager.GetString("Settings_TaskCompletionSound", resourceCulture) ?? "Task Completion Sound";
    public static string Settings_TaskCompletionSound_Desc => ResourceManager.GetString("Settings_TaskCompletionSound_Desc", resourceCulture) ?? "Play a sound when a task, milestone, or goal is completed.";
    public static string Settings_AndroidVibration => ResourceManager.GetString("Settings_AndroidVibration", resourceCulture) ?? "Vibrate on Alert";
    public static string Settings_AndroidVibration_Desc => ResourceManager.GetString("Settings_AndroidVibration_Desc", resourceCulture) ?? "Vibrate your device when a notification arrives.";
    public static string Settings_AndroidBanners => ResourceManager.GetString("Settings_AndroidBanners", resourceCulture) ?? "Pop-up Banners";
    public static string Settings_AndroidBanners_Desc => ResourceManager.GetString("Settings_AndroidBanners_Desc", resourceCulture) ?? "Show notification banners on top of running apps.";
    public static string Settings_AndroidSticky => ResourceManager.GetString("Settings_AndroidSticky", resourceCulture) ?? "Keep in Notification Drawer";
    public static string Settings_AndroidSticky_Desc => ResourceManager.GetString("Settings_AndroidSticky_Desc", resourceCulture) ?? "Keep reminders pinned in your notification bar until dismissed.";
    public static string Settings_SendTestNotification => ResourceManager.GetString("Settings_SendTestNotification", resourceCulture) ?? "Send Test Notification";

    public static string Settings_Appearance => ResourceManager.GetString("Settings_Appearance", resourceCulture) ?? "APPEARANCE & DISPLAY";
    public static string Settings_Theme => ResourceManager.GetString("Settings_Theme", resourceCulture) ?? "Color Theme";
    public static string Settings_Theme_Desc => ResourceManager.GetString("Settings_Theme_Desc", resourceCulture) ?? "Select your preferred light, dark, or system theme appearance.";
    public static string Settings_Theme_Light => ResourceManager.GetString("Settings_Theme_Light", resourceCulture) ?? "Light Mode";
    public static string Settings_Theme_Dark => ResourceManager.GetString("Settings_Theme_Dark", resourceCulture) ?? "Dark Mode";
    public static string Settings_Theme_System => ResourceManager.GetString("Settings_Theme_System", resourceCulture) ?? "Follow System";
    public static string Settings_Language => ResourceManager.GetString("Settings_Language", resourceCulture) ?? "Language / Bahasa";
    public static string Settings_Language_Desc => ResourceManager.GetString("Settings_Language_Desc", resourceCulture) ?? "Choose application display language.";
    public static string Settings_Language_System => ResourceManager.GetString("Settings_Language_System", resourceCulture) ?? "System Default";
    public static string Settings_Language_English => ResourceManager.GetString("Settings_Language_English", resourceCulture) ?? "English";
    public static string Settings_Language_Indonesian => ResourceManager.GetString("Settings_Language_Indonesian", resourceCulture) ?? "Bahasa Indonesia";

    public static string Settings_DesktopStartup => ResourceManager.GetString("Settings_DesktopStartup", resourceCulture) ?? "DESKTOP & SYSTEM TRAY";
    public static string Settings_AutoStart => ResourceManager.GetString("Settings_AutoStart", resourceCulture) ?? "Start Wadd on System Boot";
    public static string Settings_AutoStart_Desc => ResourceManager.GetString("Settings_AutoStart_Desc", resourceCulture) ?? "Automatically launch Wadd when you log in to your computer.";
    public static string Settings_StartMinimized => ResourceManager.GetString("Settings_StartMinimized", resourceCulture) ?? "Start Minimized";
    public static string Settings_StartMinimized_Desc => ResourceManager.GetString("Settings_StartMinimized_Desc", resourceCulture) ?? "Launch Wadd in the background without opening the main window.";
    public static string Settings_MinimizeToTray => ResourceManager.GetString("Settings_MinimizeToTray", resourceCulture) ?? "Minimize to System Tray";
    public static string Settings_MinimizeToTray_Desc => ResourceManager.GetString("Settings_MinimizeToTray_Desc", resourceCulture) ?? "Hide Wadd in the taskbar notification area when minimized.";
    public static string Settings_CloseToTray => ResourceManager.GetString("Settings_CloseToTray", resourceCulture) ?? "Close Button Minimizes to Tray";
    public static string Settings_CloseToTray_Desc => ResourceManager.GetString("Settings_CloseToTray_Desc", resourceCulture) ?? "Clicking the window close (X) button hides Wadd instead of exiting.";

    public static string Settings_CloudSync => ResourceManager.GetString("Settings_CloudSync", resourceCulture) ?? "CLOUD SYNC & BACKUP";
    public static string Settings_GoogleDriveSync => ResourceManager.GetString("Settings_GoogleDriveSync", resourceCulture) ?? "Google Drive Sync";
    public static string Settings_GoogleDriveSync_Desc => ResourceManager.GetString("Settings_GoogleDriveSync_Desc", resourceCulture) ?? "Sync your tasks, goals, and settings across your devices via private Google Drive storage.";
    public static string Settings_SignIn => ResourceManager.GetString("Settings_SignIn", resourceCulture) ?? "Sign In with Google";
    public static string Settings_SigningIn => ResourceManager.GetString("Settings_SigningIn", resourceCulture) ?? "Signing in...";
    public static string Settings_SigningIn_Waiting => ResourceManager.GetString("Settings_SigningIn_Waiting", resourceCulture) ?? "Waiting for Google authentication... Please complete sign-in in your browser or account prompt.";
    public static string Main_SigningInGoogle => ResourceManager.GetString("Main_SigningInGoogle", resourceCulture) ?? "Signing in with Google Account...";
    public static string Main_SignedInSuccess => ResourceManager.GetString("Main_SignedInSuccess", resourceCulture) ?? "Signed in as {0}. Connected to Google Drive.";
    public static string Main_SignInCancelled => ResourceManager.GetString("Main_SignInCancelled", resourceCulture) ?? "Sign-in cancelled.";
    public static string Settings_SignOut => ResourceManager.GetString("Settings_SignOut", resourceCulture) ?? "Sign Out";
    public static string Settings_SyncNow => ResourceManager.GetString("Settings_SyncNow", resourceCulture) ?? "Sync Now";
    public static string Settings_AiAssistant => ResourceManager.GetString("Settings_AiAssistant", resourceCulture) ?? "AI ASSISTANT & COACHING";
    public static string Settings_AiProvider => ResourceManager.GetString("Settings_AiProvider", resourceCulture) ?? "AI Provider";
    public static string Settings_AiApiKey => ResourceManager.GetString("Settings_AiApiKey", resourceCulture) ?? "API Key";
    public static string Settings_Diagnostics => ResourceManager.GetString("Settings_Diagnostics", resourceCulture) ?? "DIAGNOSTICS & SYSTEM LOGS";
    public static string Settings_ViewLogs => ResourceManager.GetString("Settings_ViewLogs", resourceCulture) ?? "View Logs";
    public static string Settings_About => ResourceManager.GetString("Settings_About", resourceCulture) ?? "About Wadd";
    public static string Settings_Version => ResourceManager.GetString("Settings_Version", resourceCulture) ?? "Version";
}
